### ISSUE TITLE
Add the auth to backend instead of Firebase

### ISSUE THREAD

**Issue by NicolasLopes7** [NKKFu/realtime-chat#1]
Since you already have a backend, why not use it to authenticate? if it is for learning reasons, firebase is pretty "deprecated" nowadays it's better to use it on the node with express. If you want, we can go to a liveshare to go ahead with this part, call me on the discord: Nicolas Lopes #0040

**Comment by NKKFu** [comment]
I really hadn't thought about this possibility of doing all of this on the backend, I'll take a closer look at it.

Thank you 😀

**Comment by NKKFu** [comment]
I did some research on JWT, OAuth and other verification methods, talked to @NicolasLopes7 and decided that I’m going to continue with Firebase Auth (because I want to use Google Sign-in and Github too) but also make a repository for JWT and OAuth only, since they are relevant issues in the area.
